# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsc" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "6035d9d0834ea0bb8fe35c88de7d748eaf38b1309394c5f9c7112e901801e86d"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "892d08e534a6e7ca2d8a91b77a1e7ae448cea0f81e787b581d6d60d4e84200bc"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c36447351e2add37eb44e1cb86f26d563f521fe2efd4a68efa9b8201a96b8037"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9722d0d7ee929afd154fdce70866915a3e081bde547ebcf50ef8bfaccd87856d"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "awsc"
  desc "CLI for AWS SSO auth, RDS/EC2/OpenSearch port forwarding via SSM, and Secrets Manager"
  homepage "https://github.com/blontic/awsc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awsc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsc"]
    end
  end
  generate_completions_from_executable "awsc", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    RDS/EC2/OpenSearch port forwarding requires the AWS Session Manager Plugin:
      brew install --cask session-manager-plugin
  EOS
end
