# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsc" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "283cb47a105b7336a798dbfeb38b2ee6fce589aed12735cffea3e62efede432a"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ce4b8294d21e2f50f3a1336c953ae19977a7ab7e558151735d9281c371b30a87"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "af5d5961c4197bd0369dcf32c24337f8777fa1b83ef0a315bb548059b2c6f58c"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "10aacb58fa436f1622fda206f57a0031994966a3e4a00ffee3784b9fe933012c"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "awsc"
  desc "CLI for AWS SSO auth, RDS/EC2/OpenSearch port forwarding via SSM, and Secrets Manager"
  homepage "https://github.com/blontic/awsc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awsc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsc"]
    end
  end
  generate_completions_from_executable "awsc", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    RDS/EC2/OpenSearch port forwarding requires the AWS Session Manager Plugin:
      brew install --cask session-manager-plugin
  EOS
end
