# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsc" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "f00bd92fcbde59c572f71af88aa0c2d2dc092a82ae0149ababcc3a1e38543c06"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d99e529c87da1f1ea04981dea822af4c09796770cf5d3944b0339dbed57823dd"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c46b50e41cc2b5281d3bbdceabfc9d05f6d0d6962674588d823439119bb64d1"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4714d23a3f955f44ac965cf64aa85742d244a422116dfd25da682c67ef76e8d4"
      url "https://github.com/blontic/awsc/releases/download/v#{version}/awsc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "awsc"
  desc "CLI for AWS SSO auth, RDS/EC2/OpenSearch port forwarding via SSM, and Secrets Manager"
  homepage "https://github.com/blontic/awsc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awsc"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsc"]
    end
  end

  generate_completions_from_executable "awsc", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    RDS/EC2/OpenSearch port forwarding requires the AWS Session Manager Plugin:
      brew install --cask session-manager-plugin
  EOS
end
